shallow_clone: false

branches:
  only: 
    - master

os:
  - Visual Studio 2017

matrix:
  fast_finish: true

environment:
  matrix:
  - { TOOLSET: 'Visual Studio 15 2017',       AMLC: 'On'  }
  - { TOOLSET: 'Visual Studio 15 2017 Win64', AMLC: 'On'  }
  - { TOOLSET: 'Visual Studio 14 2015',       AMLC: 'On'  }
  - { TOOLSET: 'Visual Studio 14 2015 Win64', AMLC: 'On'  }
  - { TOOLSET: 'Visual Studio 12 2013',       AMLC: 'Off' }
  - { TOOLSET: 'Visual Studio 12 2013 Win64', AMLC: 'Off' }
  - { TOOLSET: 'Visual Studio 11 2012',       AMLC: 'Off' }
  - { TOOLSET: 'Visual Studio 11 2012 Win64', AMLC: 'Off' }
  - { TOOLSET: 'Visual Studio 10 2010',       AMLC: 'Off' }
  - { TOOLSET: 'Visual Studio 10 2010 Win64', AMLC: 'Off' }

configuration:
  - Debug
  - Release
  - MinSizeRel
  - RelWithDebInfo

install:
  - git submodule update --init --recursive
  - cmake -G "%TOOLSET%" -DTASK_BACKEND=fiber -DAMLC="%AMLC%"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - ctest -C %CONFIGURATION% -V --timeout 30
