language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

script:
  - make build
  - ./utest.sh

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3
