language: cpp
sudo: false

matrix:
  include:
    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons: &clang35
        apt:
          sources: ['llvm-toolchain-precise-3.5', 'ubuntu-toolchain-r-test']
          packages: ['cmake', 'clang-3.5']
      env: COMPILER='clang++-3.5' BUILD_TYPE='Release'

    - os: linux
      compiler: clang
      addons: *clang35
      env: COMPILER='clang++-3.5' BUILD_TYPE='Debug'

    - os: linux
      compiler: clang
      addons: &clang36
        apt:
          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test']
          packages: ['cmake', 'clang-3.6']
      env: COMPILER='clang++-3.6' BUILD_TYPE='Release'

    - os: linux
      compiler: clang
      addons: *clang36
      env: COMPILER='clang++-3.6' BUILD_TYPE='Debug'

    - os: linux
      compiler: clang
      addons: &clang37
        apt:
          sources: ['llvm-toolchain-precise-3.7', 'ubuntu-toolchain-r-test']
          packages: ['cmake', 'clang-3.7']
      env: COMPILER='clang++-3.7' BUILD_TYPE='Release'

    - os: linux
      compiler: clang
      addons: *clang37
      env: COMPILER='clang++-3.7' BUILD_TYPE='Debug'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc48
        apt:
         sources: ['ubuntu-toolchain-r-test']
         packages: ['cmake', 'g++-4.8']
      env: COMPILER='g++-4.8' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc48
      env: COMPILER='g++-4.8' BUILD_TYPE='Debug'

    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-4.9']
      env: COMPILER='g++-4.9' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc49
      env: COMPILER='g++-4.9' BUILD_TYPE='Debug'


    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-5']
      env: COMPILER='g++-5' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc5
      env: COMPILER='g++-5' BUILD_TYPE='Debug'

    # 3/ OSX Clang Builds
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Release'

    # 4/ Coverage Build
    - os: linux
      compiler: gcc
      addons: 
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-4.6', 'lcov']
      env: 
        - |
          COMPILER='g++-4.6' BUILD_TYPE='Debug' CHECK_COVERAGE='On'
          CC_TEST_REPORTER_ID=9dc79ec67e0d8ace1a24b2fa04db9ecfa91a9c7e838c9790d5833d42f1dac663
          GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

    # 5/ AMLC Build
    - os: linux
      compiler: gcc
      addons: 
        apt:
          sources: ['george-edison55-precise-backports']
          packages: ['cmake', 'cmake-data', 'g++-4.6']
      env: 
        - |
          COMPILER='g++-4.6' AMLC='On' BUILD_TYPE='Debug'
    - os: linux
      compiler: gcc
      addons: 
        apt:
          sources: ['george-edison55-precise-backports']
          packages: ['cmake', 'cmake-data', 'g++-4.6']
      env: 
        - |
          COMPILER='g++-4.6' AMLC='On' BUILD_TYPE='Release'

before_install:
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew outdated cmake || brew upgrade cmake
    fi
    if [[ "${CHECK_COVERAGE}" == "On" ]]; then
      pip install --user cpp-coveralls
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
    fi
    set +e

before_script:
  - |
    set -e
    export CXX=${COMPILER}
    cd ${TRAVIS_BUILD_DIR}
    if [[ "${CHECK_COVERAGE}" == "On" ]]; then
      cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTASK_BACKEND=gccasm -DCHECK_COVERAGE=On
    elif [[ "${AMLC}" == "On" ]]; then
      cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTASK_BACKEND=gccasm -DAMLC=On
    else
      cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DTASK_BACKEND=gccasm
    fi
    cd Build
    set +e

script:
  - |
    set -e
    make -j 2
    if [[ "${CHECK_COVERAGE}" == "On" ]]; then
      ./cc-test-reporter before-build
      make coverage
    else
      ctest -V -j 4 --timeout 5
    fi
    set +e

after_success:
  - |
    set -e
    if [[ "${CHECK_COVERAGE}" == "On" ]]; then
      coveralls -r ../ -b . -E '/usr/.*' -E '.*/catch.hpp' -E '.*/externals/.*' -E '.*/CMakeFiles/.*'
      cp ./src/private/CMakeFiles/avm.dir/*.gcov ./ 
      ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    fi
    set +e